import { createFileRoute, Link, notFound } from "@tanstack/react-router";
import { MapPin, MessageCircle, Phone, Share2 } from "lucide-react";
import { PropertyCard } from "@/components/property-card";
import { properties } from "@/data/properties";

export const Route = createFileRoute("/properties/$id")({
  loader: ({ params }) => { const property = properties.find(p => p.id === params.id); if (!property) throw notFound(); return property; },
  head: ({ loaderData }) => ({ meta: [{ title: loaderData ? `${loaderData.title} | الرشودي` : "العقار غير موجود" }, { name: "description", content: loaderData?.description ?? "تفاصيل العقار" }, { property: "og:title", content: loaderData?.title ?? "العقار غير موجود" }, { property: "og:description", content: loaderData?.description ?? "تفاصيل العقار" }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }),
  component: Detail,
});

function Detail(){ const p=Route.useLoaderData(); const related=properties.filter(x=>x.purpose===p.purpose&&x.id!==p.id).slice(0,3); return <><section className="bg-hero pb-10 pt-32 text-hero-muted"><div className="site-container text-sm"><Link to="/">الرئيسية</Link> / <Link to={p.purpose === "بيع" ? "/sale" : "/rent"}>قسم {p.purpose}</Link> / {p.title}</div></section><section className="py-10"><div className="site-container"><div className="grid gap-8 lg:grid-cols-[1.5fr_1fr]"><img src={p.image} alt={p.title} width={1200} height={800} className="aspect-[4/3] h-full w-full rounded-lg object-cover"/><div className="self-center"><div className="flex gap-2"><span className="rounded-full bg-primary px-3 py-1 text-xs font-bold text-primary-foreground">{p.purpose}</span>{p.featured&&<span className="rounded-full bg-muted px-3 py-1 text-xs font-bold">مميز</span>}</div><h1 className="mt-5 font-display text-3xl font-black leading-tight md:text-4xl">{p.title}</h1><p className="mt-4 flex items-center gap-2 text-muted-foreground"><MapPin size={18}/>{p.district}، بريدة</p><div className="mt-7 border-y border-border py-6"><span className="text-sm text-muted-foreground">السعر</span><div className="font-display text-4xl font-black text-primary">{p.price} <small className="text-sm">ر.س {p.period}</small></div></div><dl className="mt-6 grid grid-cols-2 gap-4 text-sm"><div><dt className="text-muted-foreground">نوع العقار</dt><dd className="mt-1 font-bold">{p.type}</dd></div><div><dt className="text-muted-foreground">الغرض</dt><dd className="mt-1 font-bold">{p.purpose}</dd></div></dl><div className="mt-7 grid grid-cols-2 gap-3"><a className="inline-flex min-h-12 items-center justify-center gap-2 rounded-md bg-whatsapp px-4 font-bold text-primary-foreground" href="https://wa.me/966550818020" target="_blank" rel="noreferrer"><MessageCircle size={19}/> واتساب</a><a className="inline-flex min-h-12 items-center justify-center gap-2 rounded-md border border-border px-4 font-bold" href="tel:+966550818020"><Phone size={19}/> اتصل الآن</a></div><button onClick={()=>navigator.share?.({title:p.title,url:location.href})} className="mt-3 inline-flex min-h-11 w-full items-center justify-center gap-2 text-sm text-muted-foreground"><Share2 size={17}/> مشاركة العقار</button></div></div><div className="mt-12 max-w-3xl"><h2 className="section-title">تفاصيل العقار</h2><p className="mt-6 text-lg leading-9">{p.description}</p></div></div></section><section className="bg-muted py-16"><div className="site-container"><h2 className="section-title">عقارات مشابهة</h2><div className="mt-9 grid gap-6 md:grid-cols-3">{related.map(x=><PropertyCard key={x.id} property={x}/>)}</div></div></section></> }