import { CheckCircle2, MessageCircle, Phone } from "lucide-react";
import { useState, type FormEvent, type ReactNode } from "react";
import { PageHero } from "@/components/site";
import { Button } from "@/components/ui/button";

export function AboutPage(){return <><PageHero eyebrow="من نحن" title="خبرة محلية تصنع فرقاً في قرارك العقاري"><p>نعرف بريدة وأحياءها، ونضع خبرتنا في خدمتك للوصول إلى الصفقة المناسبة بثقة ووضوح.</p></PageHero><section className="py-20"><div className="site-container grid gap-12 md:grid-cols-2"><div><h2 className="section-title">الرشودي للعقارات</h2><p className="mt-6 leading-9 text-muted-foreground">مكتب عقاري متخصص في البيع والإيجار والتسويق العقاري في بريدة. بدأنا من فهم عميق للسوق المحلي، وبنينا علاقتنا مع عملائنا على الصدق والمتابعة وجودة الاختيار.</p></div><div className="grid gap-4">{["ترشيحات تناسب احتياجك وميزانيتك","متابعة واضحة حتى اكتمال الصفقة","معرفة دقيقة بأحياء بريدة","تسويق احترافي للعقارات"].map(x=><div key={x} className="flex items-center gap-3 border-b border-border py-4 font-bold"><CheckCircle2 className="text-primary"/>{x}</div>)}</div></div></section></>}

export function ContactPage(){return <><PageHero eyebrow="تواصل معنا" title="فريقنا جاهز لمساعدتك"><p>اختر وسيلة التواصل المناسبة وسنجيبك عن استفسارك العقاري.</p></PageHero><section className="py-20"><div className="site-container grid gap-6 md:grid-cols-2"><a href="https://wa.me/966550818020" target="_blank" rel="noreferrer" className="flex items-center gap-5 rounded-lg border border-border bg-card p-8 shadow-card"><span className="grid size-14 place-items-center rounded-full bg-whatsapp text-primary-foreground"><MessageCircle/></span><div><b className="text-xl">واتساب</b><p className="mt-1 text-muted-foreground">055 081 8020</p></div></a><a href="tel:+966550818020" className="flex items-center gap-5 rounded-lg border border-border bg-card p-8 shadow-card"><span className="grid size-14 place-items-center rounded-full bg-primary text-primary-foreground"><Phone/></span><div><b className="text-xl">اتصل بنا</b><p className="mt-1 text-muted-foreground">055 081 8020</p></div></a></div></section></>}

export function SubmitPage(){const [sent,setSent]=useState(false); const submit=(e:FormEvent)=>{e.preventDefault();setSent(true)}; return <><PageHero eyebrow="خدمات العقار" title="اعرض عقارك أو سجّل طلبك"><p>أرسل البيانات الأساسية، وسيقوم مستشار عقاري بالتواصل معك.</p></PageHero><section className="py-16"><div className="site-container max-w-3xl">{sent?<div className="rounded-lg border border-border bg-card p-12 text-center shadow-card"><CheckCircle2 className="mx-auto text-whatsapp" size={48}/><h2 className="mt-4 text-2xl font-black">تم استلام طلبك</h2><p className="mt-2 text-muted-foreground">سيتواصل معك فريقنا في أقرب وقت.</p></div>:<form onSubmit={submit} className="grid gap-5 rounded-lg border border-border bg-card p-6 shadow-card md:grid-cols-2"><Field label="الاسم الكامل"><input required className="field"/></Field><Field label="رقم الجوال"><input required type="tel" className="field"/></Field><Field label="نوع الطلب"><select className="field"><option>عرض عقار</option><option>طلب عقار</option></select></Field><Field label="نوع العقار"><select className="field"><option>شقة</option><option>فيلا</option><option>أرض</option><option>شاليه</option></select></Field><Field label="الحي"><input required className="field"/></Field><Field label="السعر المتوقع"><input className="field" inputMode="numeric"/></Field><label className="md:col-span-2 text-sm font-bold">التفاصيل<textarea rows={5} className="field mt-2 resize-none"/></label><Button className="md:col-span-2">إرسال البيانات</Button></form>}</div></section></>}
function Field({label,children}:{label:string;children:ReactNode}){return <label className="text-sm font-bold">{label}<div className="mt-2 [&_.field]:h-12 [&_.field]:w-full [&_.field]:rounded-md [&_.field]:border [&_.field]:border-input [&_.field]:bg-background [&_.field]:px-3">{children}</div></label>}